[2024-12-07T19:40:25.267+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T19:40:25.279+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medal_count_dag.check_recent_record manual__2024-12-07T19:39:36.709634+00:00 [queued]>
[2024-12-07T19:40:25.285+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medal_count_dag.check_recent_record manual__2024-12-07T19:39:36.709634+00:00 [queued]>
[2024-12-07T19:40:25.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-07T19:40:25.295+0000] {taskinstance.py:2889} INFO - Executing <Task(SqlSensor): check_recent_record> on 2024-12-07 19:39:36.709634+00:00
[2024-12-07T19:40:25.301+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4914) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T19:40:25.303+0000] {standard_task_runner.py:72} INFO - Started process 4916 to run task
[2024-12-07T19:40:25.303+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medal_count_dag', 'check_recent_record', 'manual__2024-12-07T19:39:36.709634+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpzri229rv']
[2024-12-07T19:40:25.304+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask check_recent_record
[2024-12-07T19:40:25.335+0000] {task_command.py:467} INFO - Running <TaskInstance: medal_count_dag.check_recent_record manual__2024-12-07T19:39:36.709634+00:00 [running]> on host a693d8a2436c
[2024-12-07T19:40:25.549+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medal_count_dag' AIRFLOW_CTX_TASK_ID='check_recent_record' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T19:39:36.709634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T19:39:36.709634+00:00'
[2024-12-07T19:40:25.550+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-07T19:40:25.551+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-07T19:40:25.552+0000] {logging_mixin.py:190} INFO - Current task name:check_recent_record state:running start_date:2024-12-07 19:40:25.279985+00:00
[2024-12-07T19:40:25.553+0000] {logging_mixin.py:190} INFO - Dag name:medal_count_dag and current dag run status:running
[2024-12-07T19:40:25.554+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T19:40:25.561+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:25.564+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:40:25.570+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:25.798+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:40:25.844+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:40:30.898+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:30.899+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:40:30.904+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:31.117+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:40:31.162+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:40:36.216+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:36.217+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:40:36.223+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:36.438+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:40:36.483+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:40:41.536+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:41.537+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:40:41.543+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:41.766+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:40:41.812+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:40:46.864+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:46.865+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:40:46.870+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:47.080+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:40:47.124+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:40:52.181+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:52.182+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:40:52.188+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:52.399+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:40:52.442+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:40:57.495+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:57.496+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:40:57.502+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:40:57.723+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:40:57.771+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:41:02.829+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:02.830+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:41:02.836+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:03.061+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:41:03.108+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:41:08.164+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:08.165+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:41:08.171+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:08.391+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:41:08.435+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:41:13.482+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:13.483+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:41:13.487+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:13.702+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:41:13.747+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:41:18.800+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:18.801+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:41:18.805+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:19.013+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:41:19.057+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:41:24.108+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:24.110+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:41:24.116+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:24.328+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:41:24.373+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:41:29.425+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:29.427+0000] {sql.py:101} INFO - Poking: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
     (with parameters None)
[2024-12-07T19:41:29.432+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:41:29.652+0000] {sql.py:544} INFO - Running statement: 
    SELECT COUNT(*) 
    FROM medal_count_vvd 
    WHERE created_at >= NOW() - INTERVAL 30 SECOND;
    , parameters: None
[2024-12-07T19:41:29.698+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-07T19:41:29.743+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 64.19094412100094 seconds exceeds the specified timeout of 60.0.
[2024-12-07T19:41:29.750+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-07T19:41:29.751+0000] {logging_mixin.py:190} INFO - Task start:2024-12-07 19:40:25.279985+00:00 end:2024-12-07 19:41:29.750196+00:00 duration:64.470211
[2024-12-07T19:41:29.751+0000] {logging_mixin.py:190} INFO - Task:<Task(SqlSensor): check_recent_record> dag:<DAG: medal_count_dag> dagrun:<DagRun medal_count_dag @ 2024-12-07 19:39:36.709634+00:00: manual__2024-12-07T19:39:36.709634+00:00, state:running, queued_at: 2024-12-07 19:39:36.720879+00:00. externally triggered: True>
[2024-12-07T19:41:29.752+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 64.19094412100094 seconds exceeds the specified timeout of 60.0.
[2024-12-07T19:41:29.752+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=medal_count_dag, task_id=check_recent_record, run_id=manual__2024-12-07T19:39:36.709634+00:00, execution_date=20241207T193936, start_date=20241207T194025, end_date=20241207T194129
[2024-12-07T19:41:29.761+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T19:41:29.762+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task check_recent_record (Sensor has timed out; run duration of 64.19094412100094 seconds exceeds the specified timeout of 60.0.; 4916)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 64.19094412100094 seconds exceeds the specified timeout of 60.0.
[2024-12-07T19:41:29.798+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-07T19:41:29.810+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T19:41:29.813+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
