[2024-12-07T19:11:13.225+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T19:11:13.238+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medal_count_dag.pick_medal_task manual__2024-12-07T19:11:06.363937+00:00 [queued]>
[2024-12-07T19:11:13.246+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medal_count_dag.pick_medal_task manual__2024-12-07T19:11:06.363937+00:00 [queued]>
[2024-12-07T19:11:13.247+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-07T19:11:13.258+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): pick_medal_task> on 2024-12-07 19:11:06.363937+00:00
[2024-12-07T19:11:13.265+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4405) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T19:11:13.266+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medal_count_dag', 'pick_medal_task', 'manual__2024-12-07T19:11:06.363937+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmphsk735hi']
[2024-12-07T19:11:13.266+0000] {standard_task_runner.py:72} INFO - Started process 4407 to run task
[2024-12-07T19:11:13.267+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask pick_medal_task
[2024-12-07T19:11:13.305+0000] {task_command.py:467} INFO - Running <TaskInstance: medal_count_dag.pick_medal_task manual__2024-12-07T19:11:06.363937+00:00 [running]> on host a693d8a2436c
[2024-12-07T19:11:13.503+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medal_count_dag' AIRFLOW_CTX_TASK_ID='pick_medal_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T19:11:06.363937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T19:11:06.363937+00:00'
[2024-12-07T19:11:13.505+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-07T19:11:13.506+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-07T19:11:13.507+0000] {logging_mixin.py:190} INFO - Current task name:pick_medal_task state:running start_date:2024-12-07 19:11:13.239528+00:00
[2024-12-07T19:11:13.508+0000] {logging_mixin.py:190} INFO - Dag name:medal_count_dag and current dag run status:running
[2024-12-07T19:11:13.509+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T19:11:13.509+0000] {baseoperator.py:416} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-12-07T19:11:13.511+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 61, in check_medal_type
    if medal_type == 'Bronze':
       ^^^^^^^^^^
NameError: name 'medal_type' is not defined
[2024-12-07T19:11:13.526+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-07T19:11:13.527+0000] {logging_mixin.py:190} INFO - Task start:2024-12-07 19:11:13.239528+00:00 end:2024-12-07 19:11:13.526076+00:00 duration:0.286548
[2024-12-07T19:11:13.528+0000] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): pick_medal_task> dag:<DAG: medal_count_dag> dagrun:<DagRun medal_count_dag @ 2024-12-07 19:11:06.363937+00:00: manual__2024-12-07T19:11:06.363937+00:00, state:running, queued_at: 2024-12-07 19:11:06.380392+00:00. externally triggered: True>
[2024-12-07T19:11:13.528+0000] {logging_mixin.py:190} INFO - Failure caused by name 'medal_type' is not defined
[2024-12-07T19:11:13.529+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=medal_count_dag, task_id=pick_medal_task, run_id=manual__2024-12-07T19:11:06.363937+00:00, execution_date=20241207T191106, start_date=20241207T191113, end_date=20241207T191113
[2024-12-07T19:11:13.537+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T19:11:13.538+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task pick_medal_task (name 'medal_type' is not defined; 4407)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 61, in check_medal_type
    if medal_type == 'Bronze':
       ^^^^^^^^^^
NameError: name 'medal_type' is not defined
[2024-12-07T19:11:13.563+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-07T19:11:13.584+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T19:11:13.589+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
